### ISSUE TITLE
[BUG]  gcc-12.2 on Arch Linux does not link w/o -ltbb

### ISSUE THREAD

**Issue by arabusov** [hsutter/cppfront#158] opened 2022-12-05 22:13 UTC
**Describe the bug**
Gcc-12.2 on current Arch Linux requires the `-ltbb` option to link a code generated by `cppfront`  without errors.

**To Reproduce**

Sample code is provided just for an example, the behavior should be similar with any valid cpp2 code
```
main: () -> int = {
    words: std::vector<std::string> = (
        "one", "two", "three" );
    print_and_decorate(words[3]);
}

print_and_decorate: (thing: _) =
    std::cout << "[" << thing << "]" << std::endl;
```

The produced C++ code:
```
// ----- Cpp2 support -----
#define CPP2_USE_MODULES         Yes
#include "cpp2util.h"


#line 1 "dec.cpp2"
[[nodiscard]] auto main() -> int;
#line 7 "dec.cpp2"
auto print_and_decorate(auto const& thing) -> void;

//=== Cpp2 definitions ==========================================================

#line 1 "dec.cpp2"
[[nodiscard]] auto main() -> int{
    std::vector<std::string> words { 
        "one", "two", "three" }; 
    print_and_decorate(cpp2::assert_in_bounds(words, 3));
}

auto print_and_decorate(auto const& thing) -> void { 
    std::cout << "[" << thing << "]" << std::endl; }
```

Compilation goes as follows:
```
[cppfront]$ cppfront dec.cpp2 -p -s
dec.cpp2... ok (all Cpp2, passes safety checks)

[cppfront]$ g++ -std=c++20 -o dec dec.cpp
/usr/bin/ld: /tmp/ccInhq4C.o: in function `tbb::detail::d1::execution_slot(tbb::detail::d1::execution_data const&)':
dec.cpp:(.text._ZN3tbb6detail2d114execution_slotERKNS1_14execution_dataE[_ZN3tbb6detail2d114execution_slotERKNS1_14execution_dataE]+0x14): undefined reference to `tbb::detail::r1::execution_slot(tbb::detail::d1::execution_data const*)'
/usr/bin/ld: /tmp/ccInhq4C.o: in function `tbb::detail::d1::current_thread_index()':
dec.cpp:(.text._ZN3tbb6detail2d120current_thread_indexEv[_ZN3tbb6detail2d120current_thread_indexEv]+0xe): undefined reference to `tbb::detail::r1::execution_slot(tbb::detail::d1::execution_data const*)'
collect2: error: ld returned 1 exit status
[cppfront]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (GCC) 
```

When I add the `-ltbb` option, Gcc-12 compiles and links the code. The binary produces the expected result:

```
[cppfront]$ g++ -std=c++20 -o dec dec.cpp -ltbb
[cppfront]$ ./dec 
Bounds safety violation: out of bounds access attempt detected
terminate called without an active exception
Aborted (core dumped)
```

A simple fix would be to point out in README that generated code needs to be linked against the TBB library if the Gcc-12 backend is used. Additionally, the TBB library should be installed in advance.

**Comment by hsutter** [comment] 2022-12-05 22:42
Thanks.

> generated code needs to be linked against the TBB library if the Gcc-12 backend is used. Additionally, the TBB library should be installed in advance.

That seems to be new, I haven't encountered that with g++ 10. I'm guessing TBB is Intel's TBB (Threading Building Blocks)? The generated `.cpp` code above should be just portable C++ code and standard library headers... shouldn't vanilla gcc 12 compile such code without also installing TBB?

I did try to reproduce this result, but haven't been able to: In Godbolt CE, I pasted the generated `.cpp` code above into Godbolt CE, replaced `#include "cpp2util.h"` with the contents of `cpp2util.h`, and compiled it with gcc 12.2 and trunk, and it all worked. Here's an [example using gcc 12.2](https://godbolt.org/z/c5TrEhh9a).

Can you make a repro that fails on Godbolt? Or could it be something about your local machine's environment, perhaps you have TBB installed and that made a change?

**Comment by JohelEGP** [comment] 2022-12-05 22:44
The CE instance probably doesn't use Arch Linux.

**Comment by filipsajdak** [comment] 2022-12-05 22:51
As stated here: https://github.com/wolfpld/tracy/issues/48#issuecomment-645685669

```
There is no (direct) dependency on TBB in Tracy. The implementation of parallel algorithms in libstdc++ depends on TBB and is horribly broken, as you need to manually link with the library. Unless you're working with an older version of libstdc++, which doesn't support parallel algorithms, in which case it's not needed. It's a mess. Just working out-of-the-box is in another castle.
```

Probably it is a fault of the standard library you link against.

**Comment by arabusov** [comment] 2022-12-05 22:59
@filipsajdak thanks for the comment, I agree that probably the actual "bug" is on the Gcc side.

With Clang-14.0.6 everything works just fine:

```
[cppfront]$ cppfront dec.cpp2 -p -s
dec.cpp2... ok (all Cpp2, passes safety checks)

[cppfront]$ clang++ -o dec -std=c++20 dec.cpp
./dec[arabusov@r2-d2 cppfront]$ ./dec
Bounds safety violation: out of bounds access attempt detected
terminate called without an active exception
Aborted (core dumped)
```

**Comment by hsutter** [comment] 2022-12-05 23:27
OK, one last idea though:

Perhaps it might be triggered by one of the many headers that `-p` pulls in to simulate C++23 `import std;` on a compiler that doesn't support it yet. Could you try this please:

- Take the [mostly-minimalized code in this Godbolt example](https://godbolt.org/z/szh5ehfYr) and try compiling it in your environment, and see if it can trigger the error again.
- If you can trigger the error with that code, then could you try successively removing some of the standard `#include`s in that long list to narrow down and see which one (or just a few) standard headers may be causing the problem?

If it's just one or a few headers, and they're lesser-used headers, then I could add an `#ifdef` to not bring those in on GCC 12.2 in the `-p` simulation of `#import std;` on a non-C++23 compiler.

**Comment by arabusov** [comment] 2022-12-06 00:01
If I remove `#include <execution>` from the example you've provided the code compiles:

```
[gcc]$ g++ -std=c++20 76.cpp -o 76.exe
[gcc]$ ./76.exe 
Bounds safety violation: out of bounds access attempt detected
terminate called without an active exception
Aborted (core dumped)
```

[godbolt](https://godbolt.org/z/Td3ahY7Ec)

**Comment by hsutter** [comment] 2022-12-06 00:41
Aha, so `<execution>` is the culprit. Thanks.

I know [Intel contributed the parallel algorithms a few years ago](https://gcc.gnu.org/legacy-ml/libstdc++/2017-11/msg00114.html)... do you remember what GCC release added the TBB dependency, was it 11? (I don't hit this in g++-10, and you're using 12.2, but I'm not sure where Intel's parallel algorithms submission was merged... let me assume it was 11 for now.)

So the `#ifdef` would be something like this I think:

    #if defined(__GNUC__) && __GNUC__ < 11
        #include <execution>
    #endif

**Closed** 2022-12-06 00:44 UTC
Labels: bug, question

**Comment by JohelEGP** [comment] 2022-12-06 00:48
See https://github.com/hsutter/cppfront/commit/52cc059f836343b9289700486732a63128f7f472#commitcomment-92111503:
> This only includes if for GCC, _not_ exclude it for only GCC >= 11.
> It should be `#if not defined(__GNUC__) || __GNUC__ < 11`.

**Comment by hsutter** [comment] 2022-12-06 00:51
@JohelEGP D'oh! Thanks, re-fixed in later commit.

@arabusov Can you confirm that this commit resolves the problem for you?

Also is `__GNUC__ < 11` the right version? This probably doesn't matter since most code won't try to use `<execution>` but I'd like to keep the workaround as accurate as possible.

**Comment by JohelEGP** [comment] 2022-12-06 00:54
Actually, the fix should be looking at libstdc++, not GCC or Clang.

**Comment by hsutter** [comment] 2022-12-06 01:00
Re Clang: I've done that, but I'm actually not sure about that because this is about the standard library (not the language compiler) and Clang works with both libstd++ and libc++. Now that I'm thinking about it, probably better would be to check for libstd++ `__GLIBCXX__` rather than GCC.

**Comment by hsutter** [comment] 2022-12-06 01:02
Ah, racing comment! :) So what's the right version of `__GLIBCXX__` to use as a cutoff, `20210101` perhaps?

**Comment by JohelEGP** [comment] 2022-12-06 01:17
I gather from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101228#c4 that it was added in version 9.1 (see https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017, "The Parallelism TS Should be Standardized", "P0024R2"). https://gcc.gnu.org/onlinedocs/gcc-4.8.5/libstdc++/manual/manual/abi.html instructs to follow https://gcc.gnu.org/develop.html#timeline for the value of `__GLIBCXX__` in version 9.1. It's dated 2019-05-03, so the value should be `< 20190503`.

**Comment by JohelEGP** [comment] 2022-12-06 01:20
The README uses GCC 10, so maybe `<execution>` can be unconditionally excluded for libstdc++.

**Comment by arabusov** [comment] 2022-12-06 06:59
@hsutter I checked out the latest `include/cpp2util.h` and the link error is gone. Thank you!

**Comment by hsutter** [comment] 2022-12-06 17:46
OK, I think you're right, unconditionally excluding it is best.

FWIW I'm testing with g++-10 that's the default in Ubuntu 20.04 LTS, so my guess is that they probably also install TBB and that's probably why I didn't encounter it before. But I don't want users who haven't gotten it automatically to have the problem for a header that's rarely used.

Thanks, everyone!
