### ISSUE TITLE
[BUG] anonymous functions and things inside decltype should never be forward declared

### ISSUE THREAD

**Issue by farmerpiki** [hsutter/cppfront#485] opened 2023-06-02 00:12 UTC
**Describe the bug**
I think anonymous functions should never be forward declared, and IMHO decltype should not be implied for them when using inside a type alias (and possibly other scenarios as well)

currently there's no usable equivalent to the cpp1 syntax for this that works
using pq_conn_ptr = std::unique_ptr<PGconn, decltype([](PGconn *ptr) { PQfinish(ptr); })>;

**To Reproduce**
1. Sample code - distilled down to minimal essentials please
I tried this instead
pq_conn_ptr : type == std::unique_ptr<PGconn, decltype(: (ptr : *PGconn) = { PQfinish(ptr); })>;
and using it just as
p: pq_conn_ptr = ();
2. Command lines including which C++ compiler you are using
cppfront and g++-13 but I guess the issue would be with any compiler cause it's caused by the generated code
3. Expected result - what you expected to happen
I expected it to generate the above using declaration
4. Actual result/error
using pq_conn_ptr = std::unique_ptr<PGconn,decltype([](PGconn* ptr) -> void;)>;
the error is that the body of the lambda is missing

**Comment by JohelEGP** [comment] 2023-06-02 00:14
Seems like a duplicate of #385.

**Comment by JohelEGP** [comment] 2023-06-02 00:16
But I think it actually isn't.
This is a case where it can be valid.
A type alias can't be forward declared,
so the function expression can be emitted in full without problems.

**Comment by farmerpiki** [comment] 2023-06-02 00:40
also I'm not trying to ban the use of this (as that bug suggests), as this is valid syntax (at least the cpp1 version) and I think should be representable in the new syntax
also do you guys think I should make a new suggestion to automatically use decltype for lambdas inside type alias definitions like this, I think it's the only valid way to use a lambda in a type if you also use decltype on it

**Comment by JohelEGP** [comment] 2023-06-02 00:46
> Do you guys think I should make a new suggestion to automatically use decltype for lambdas inside type alias definitions like this, I think it's the only valid way to use a lambda in a type if you also use decltype on it?

You can definitely use it to initialize a NTTP: <https://cpp2.godbolt.org/z/ja8x6E76j>.

**Comment by farmerpiki** [comment] 2023-06-02 01:12
I was suggesting it just for types, your example is a NTTP as in non-type template parameter.
Also I'm not sure your example proves much as in this one https://cpp2.godbolt.org/z/v48x1Wa5G it's a very clearly different function and it still works (as in code is generated for it and it compiles)

**Comment by JohelEGP** [comment] 2023-06-02 01:23
Oh, so is your suggestion is to replace them with their type?
I misunderstood it as automatically inserting `decltype()` around it
because they're not valid NTTPs (you said "can't be used any other way").

Either way, I don't see how it can generally work.
The indirection through the `decltype()` changes nothing.

A function expression in a declaration's signature just doesn't mix with order independence.

**Comment by farmerpiki** [comment] 2023-06-02 01:36
You are right, it doesn't mix with order independence.
All I want is a way to express this in a the new syntax, the other thing was a question and I got my answer, I was wrong in thinking there are no other uses.

before allowing the decltype I just could not declare a type for this (my initial example):
using pq_conn_ptr = std::unique_ptr<PGconn, decltype([](PGconn *ptr) { PQfinish(ptr); })>;

I had to always use auto as return type and use CTAD to initialize the unique_ptr everywhere, it gets ugly pretty quickly compared to being able to declare a type and have a single lambda everywhere, also the compiled code is shorter because the linker can't figure out that the lambdas are all the same without the newer decltype syntax.

**Comment by JohelEGP** [comment] 2023-06-02 01:41
Well, here we have a valid use-case.
The bug seems to be that a function expression is attempted to be forward-declared.

**Comment by farmerpiki** [comment] 2023-06-02 01:51
here's a cleaner example so people don't bother with libpq or modifying the example by hand
https://cpp2.godbolt.org/z/cE856d3jn

cleaned up code:
```
using fptr = std::unique_ptr<FILE, decltype([](FILE *ptr) { fclose(ptr); })>;

main: () = {
    f: fptr = (fdopen(0, "r"));
}

```
can you point me where to look if I want to fix this? I might have some time over the weekend

**Comment by JohelEGP** [comment] 2023-06-02 02:52
https://github.com/hsutter/cppfront/blob/4376132243543f000a9c698b29a1a6202797f046/source/cppfront.cpp#L1288-L1290
During phase 1,
when a function is being emitted,
if it's actually a function expression,
checks for phase 2 should be ignored.

**Closed** 2023-09-02 00:03 UTC
Labels: bug
