### ISSUE TITLE
Scoping and overloading

### ISSUE THREAD

**Issue by define-private-public** [hsutter/cppfront#28] opened 2022-09-29 21:53 UTC
Hi Mr. Sutter.  Really loved the talk (finished watching today) and appreciate your work on the language and C++ in general.

---

About 3 minutes ago I just got off of a Skype call with my brother.  He's still new to C++, whereas I've been with the language for around 14-ish years.  He was having some trouble with a segfault in a very simple project and it took me a while to figure out what the exact issue was.  This is definitely something I've shot myself in the foot with quite a bit; or at least it created all sorts of headaches when it came to debugging.

In short, here's what we had up:

ComplexWidget.hpp:
```
class CompexWidget : public QWidget {

public:
    ComplexWidget();

private:
    QLineEdit *m_numberValue;
};
```

ComplexWidget.cpp:
```
ComplexWidget::ComplexWidget() : ...
{
    QLineEdit *m_numberValue = new QLineEdit("");
}

...

void ComplexWidget::onButtonClicked()
{
    int n = m_numberValue->text().toInt();
}
```

Whenever he pressed his button, hoping to get the value from `m_numberValue` and parse it to an integer, we were treated with a segmentation fault.  It wasn't until some debugging did I spot what the true problem was.  **In the constructor, he re-declared `m_numberValue`**.  I told him to get rid of the `QLineEdit *` in the constructor and then his program worked, with no segmentation faults.  This actually took me a little bit to hunt down as well.  **Not once, when we were compiling, was there any warning about this.**  This is an issue related to scoping.

As for what to do to prevent this, making things safer, my proposal is:  **Don't allow programmers to re-declare variable names.  Give a compilation error instead.**  I'm sure some other rules could be added to this.

**Comment by BenHanson** [comment] 2022-09-30 10:57
I have bespoke SA at work to prevent these kind of members being left uninitialised in header files. Maybe this approach could be used and then a special tag for deferred initialisation? Hopefully this then covers multiple classes of errors.

Also does the control in this example even need to be a pointer? (Or is this some weird QT requirement? It's a long time since I used it)

**Comment by dkaszews** [comment] 2022-09-30 18:48
Don't really see it being relevant, with GCC/Clang on `-Wextra` and MSVC with `-W4` will warn you about shadowed fields or arguments. For this code it may also complain about not using initializer list, which would also fix the issue. So the problem is already resolved with existing tools, you just need to enable those warnings and treat them as errors.

**Comment by BenHanson** [comment] 2022-10-01 10:01
I still think that insisting you initialise types at the point of declaration (unless you opt out) is an improvement though.

**Comment by dkaszews** [comment] 2022-10-01 13:02
Which is already a thing that C++ compilers do if you enable warnings.

**Comment by BenHanson** [comment] 2022-10-01 15:50
> Which is already a thing that C++ compilers do if you enable warnings.

But not the opt out part?

I'm coming at this from the point of view that uninitialised (for POD types) is the wrong default, but some people will insist they need the option to have them be uninitialised. The D programming language uses the same approach I am talking about.

**Comment by hsutter** [comment] 2022-10-05 00:50
Thanks! I'll keep this in mind for when I add classes.

I agree this is problematic for a member function that redeclares a class member. Ouch! I like the idea of diagnosing that for all member functions, and for constructors I think it will actually fall out from the way I intend to implement constructors.

But in other cases I worry that banning all shadowing would harm toolability, such as refactoring. For example, a function should be able to have a local name for its own internal use even if that same name is also a name in scope in the namespace (immediate or nested) enclosing the function. If it can't do that, then a refactoring tool moving a function from one place to another could cause the code to be illegal in the new place only because of shadowing a name in the vicinity of that new place but which isn't relevant to the operation of the function. But I'll give it more thought. Thanks for the suggestion!

**Closed by hsutter** 2022-10-05 00:50 UTC
Labels: suggestion
