### ISSUE TITLE
`regression_tests/test_output` has not been updated

### ISSUE THREAD

**Issue by ntrel** [hsutter/cppfront#383] opened 2023-04-18 17:19 UTC
(I'm still trying to [figure out how](https://github.com/modern-cmake/cppfront/issues/64#issuecomment-1513486297) to get `ctest` to work).

Tests are failing after b34f23a: https://github.com/modern-cmake/cppfront/actions/workflows/ci.yml

Just as a random example:
```diff
@@ -1,5 +1,4 @@
 
-#define CPP2_USE_MODULES         Yes
 
 //=== Cpp2 type declarations ====================================================
 
@@ -24,7 +23,7 @@ auto print_and_decorate(auto const& thing) -> void;
 #line 2 "pure2-bounds-safety-span.cpp2"
 [[nodiscard]] auto main() -> int
 {
-    std::vector<std::string> words {"decorated", "hello", "world"}; 
+    std::vector<std::std::move(string)> words {"decorated", "hello", "world"}; 
 
     std::span<std::string> s {words}; 
```

**Comment by filipsajdak** [comment] 2023-04-19 20:27
Hm... I have checked the @alexreinking repo, and failures might be due to wrong configuration of the CI pipeline:
```
[2/3] Building CXX object CMakeFiles\test-case.dir\_cppfront\pure2-bounds-safety-span.cpp.obj
FAILED: CMakeFiles/test-case.dir/_cppfront/pure2-bounds-safety-span.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\HostX64\x64\cl.exe  /nologo /TP  -external:ID:\a\cppfront\cppfront\_local\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -MD /experimental:module -std:c++20 /showIncludes /FoCMakeFiles\test-case.dir\_cppfront\pure2-bounds-safety-span.cpp.obj /FdCMakeFiles\test-case.dir\ /FS -c D:\a\cppfront\cppfront\build\regression-tests\pure2-bounds-safety-span\build\_cppfront\pure2-bounds-safety-span.cpp
D:\a\cppfront\cppfront\_local\include\cpp2util.h(48): fatal error C1011: cannot locate standard module interface. Did you install the library part of the C++ modules feature in VS setup?
ninja: build stopped: subcommand failed.
```

So, it complains about:
```
cpp2util.h(48): fatal error C1011: cannot locate standard module interface. Did you install the library part of the C++ modules feature in VS setup?
```

The newest builds are failing due to change from `load.h` to `io.h` : 
```
CMake Error at CMakeLists.txt:28 (add_executable):
  Cannot find source file:

    D:/a/cppfront/cppfront/cppfront/source/load.h
```

I have created the issues in modern-cmake/cppfront repository to let @alexreinking know about them: https://github.com/modern-cmake/cppfront/issues/67 & https://github.com/modern-cmake/cppfront/issues/68

**Comment by ntrel** [comment] 2023-04-22 17:00
> Do you have a repro test case that generates that bad code?

On that I just ran my cppfront build on `regression_tests/pure2-bounds-safety-span.cpp2` and diff'd it with the .cpp one in `test_output`. I may be doing something wrong.

**Comment by hsutter** [comment] 2023-04-22 19:16
Odd. If you just build `cppfront.exe` itself using [the instructions here](https://github.com/hsutter/cppfront#how-do-i-build-cppfront) and then use it to build that file you should get the same `.cpp` that's checked in. That's what I do before every commit.

I'll close this for now, but please reopen if you get a repro using those steps.

**Closed by hsutter** 2023-04-22 19:16 UTC
Labels: question - further information requested

**Comment by hsutter** [comment] 2023-04-22 19:34
BTW another thing you can try is Goldbolt and select language "Cpp2 / cppfront."

When I cut-and-paste the code from `regression_tests/pure2-bounds-safety-span.cpp2` there, it looks fine:
https://godbolt.org/z/zs3ashW94

I don't know how it could try to stick a `move` into a template parameter list, but I also tried to trick it by having a local variable named `string` and that doesn't seem to fool it: 
https://godbolt.org/z/v4jdWTMeq

So for now I don't have a repro, but please reopen if you can make a repro that works on Godbolt. If it ever does bad code gen like that, I'd want to know about it and fix it. Thanks for taking the time to look into this!

**Comment by alexreinking** [comment] 2023-05-31 18:41
I've updated the modern-cmake/cppfront repo to work with the new header structure. However, the regression tests are still failing on msvc because it looks like the `windows-2022` runner has a broken Visual Studio installation and the `windows-2019` runner's libraries/headers are too old to use.
