### ISSUE TITLE
[SUGGESTION] Allow `main()` to be `constexpr` and to be called from user code

### ISSUE THREAD

**Issue by LocalSpook** [hsutter/cppfront#1054] opened 2024-04-19 05:04 UTC
In C++, `main` cannot be called from user code and cannot be constexpr (section \[basic.start.main\] of the standard).

The workaround is to define `main` to do nothing but delegate to an ordinary function without these restrictions:

```cpp
// Compute 10^argc, recursively.
constexpr int my_main(const int argc, const char * const * const argv) {
	return (argc <= 0) ? 1 : 10 * my_main(argc - 1, argv + 1);
}

// Test main() at compile time.
static_assert(my_main(2, (const char *[]){"a", "b", nullptr}) == 100);

int main(int argc, char ** argv) {
	return my_main(argc, argv);
}
```

I propose that cppfront does this automatically, making something like the following code valid:

```cpp
main: (args) -> int == /* note ==, not = */ (args.argc <= 0) ? 1 : 10 * main(args.argc - 1, args.argv + 1);
```

This would reduce `main`'s inconsistency and eliminate potential undefined behavior.

Cppfront would have to
  - generate the delegating `main`;
  - translate all uses of `main` in Cpp2 code to the custom `main`; and
  - make `args_t` constexpr.

**Comment by jcanizales** [comment] 2024-04-22 22:28
Other than consistency (which is a good reason on its own), are there actual use cases for this?

**Comment by SebastianTroy** [comment] 2024-04-23 06:59
Does constexpr main make sense given that args are  runtime parameters by design?

**Comment by LocalSpook** [comment] 2024-04-23 17:34
The best example I've been able to come up with is the POSIX `test`/`[` command. It exists to return 0 if the given condition is true, 1 if false. With constexpr `main`, you could test a subset of its functionality at compile time.

```cpp
static_assert(main("[", "-2", "-le", "0", "-a", "foo", "=", "foo", "]") == 0);
```

**Comment by Xeverous** [comment] 2024-06-21 17:59
@LocalSpook True but in such case you might aswell go the 2-layer main approach and just test the inner function.

I think that the workaround to this issue is so easy to come up with and so trivial to implement that it is not worth the bureaucratic effort of changing the standard.

On the contrary, is there any "official justification" why the main function has such special rules?

**Comment by hsutter** [comment] 2024-06-22 23:31
Thanks! I'm not against doing this, but I don't think it's one of the more pressing safety or simplicity issues with C++ and I need to prioritize... so I'll close this for the time being in favor of other bug fixes and new features. But I appreciate the suggestion, and thanks for understanding!

**Closed by hsutter** 2024-06-22 23:31 UTC
Labels: suggestion
