### ISSUE TITLE
[QUESTION] Template parameters not using `cpp2::in<T>`.

### ISSUE THREAD

**Issue by leejy12** [hsutter/cppfront#264] opened 2023-03-04 04:51 UTC
As of commit 91e1d7981cbba01d0b559bf0c2ac6ada7d01816d, this cpp2 code 
```
foo: <T: type> (t: T) = {

}
```
is compiled into
```cpp
template<typename T> auto foo(T const& t) -> void{

}
```

Is there a reason why the type of `t` is `T const&` and not `cpp2::in<T>`?

**Comment by hsutter** [comment] 2023-03-04 16:36
Yes -- it's only because `cpp2::in<T>` would make `T` non-deducible, meaning that calls like `foo(1)` wouldn't work.

`cpp2::in<T>` works elegantly 

I could do this, which is clear and would work fine because exactly one overload would be callable for any `T` (assume `prefer_pass_by_value<T>` does the same test `in<T>` does):

```
template<typename T> auto foo(T const t) -> void
    requires prefer_pass_by_value<T>
    { ... }
template<typename T> auto foo(T const& t) -> void
    requires !prefer_pass_by_value<T>
    { ... }
```

... but the problem isn't that it doubles the number of overloads, the problem is it requires _combinatorial_ overloads (2^N overloads for N such parameters), which feels prohibitive.

If someone knows an easy way to get the pass-small-trivial-by-value optimization, I'm all ears!

**Comment by hsutter** [comment] 2023-03-04 17:10
Besides, I think normally in Cpp2 this wouldn't come up, because you wouldn't write `f: <T> (t: T) = ...`, but rather you'd just write `f: (t) = ...` which is equivalent (except that you have the name `T`, but that's easy to get with `decltype(t)`, and I'll probably add `typeof(t)` to give a nicer name to `CPP2_TYPEOF(t)`...)

**Comment by JohelEGP** [comment] 2023-03-04 17:11
Perhaps https://www.boost.org/doc/libs/1_81_0/libs/utility/doc/html/utility/utilities/call_traits.html#utility.utilities.call_traits.examples.example_4_optimising_fill can serve as inspiration. Since [<boost/call_traits.hpp>](https://www.boost.org/doc/libs/1_81_0/boost/call_traits.hpp) feels similar to `cpp2::in`, I took a look to see how they handle templates.

Perhaps instead of overloads, you could wrap the body in an IILE with correct parameter passing:
```C++2
foo: <T: type> (t: T) = {
  body;
}
```
```C++
template<typename T> auto foo(T&& __t) -> void{
  [](cpp2::in<T> t) {
    body;
  }(std::forward<T>(__t));
}
```

**Comment by jcanizales** [comment] 2023-03-04 23:51
What's an IILE? :slightly_smiling_face:

**Comment by hsutter** [comment] 2023-03-05 00:01
Thanks all... @JohelEGP I'm not sure that achieves the purpose which is to avoid the reference... it would still pass by reference, and then add another copy (of the reference or of the object) on top of that, no?

I'm going to close this for now as it's the currently intended implementation and I think the question has been answered. Thanks!

**Closed by hsutter** 2023-03-05 00:01 UTC
Labels: help wanted, question - further information requested

**Comment by JohelEGP** [comment] 2023-03-05 00:24
> What's an IILE? slightly_smiling_face

An immediately invoked lambda expression.

> Thanks all... @JohelEGP I'm not sure that achieves the purpose which is to avoid the reference... it would still pass by reference, and then add another copy (of the reference or of the object) on top of that, no?

That's right.

I thought it might still be beneficial. In the linked example, the call to the algorithm's implementation passes by copy, which enables optimizations.

But such an approach doesn't mix well with non-copyable non-movable `T`. A prvalue `T` argument is materialized to initialize the outer forwarding reference. If using `cpp2::in` determines `T` is a candidate for copy, the code is ill-formed.

**Comment by JohelEGP** [comment] 2023-03-05 14:30
> I could do this in cppfront in the following way, which is clear and would work fine because exactly one overload would be callable for any `T` (assume `prefer_pass_by_value<T>` does the same test `in<T>` does), but has a visible drawback:
> 
> ```
> template<typename T> auto foo(T const t) -> void
>     requires prefer_pass_by_value<T>
>     { ... }
> template<typename T> auto foo(T const& t) -> void
>     requires !prefer_pass_by_value<T>
>     { ... }
> ```
> 
> ... and the drawback isn't even that it doubles the number of overloads, the drawback is it requires generical a _combinatorial_ number of overloads (2^N overloads for N such parameters), which feels prohibitive.

This is something that https://wg21.link/P1167R0 would've made trivially possible.

> ```C++
> // Example 2: Allow Deduction Guides for Function Templates
> template <typename T> void f(T t); // Implement here. No need to delegate
> template <typename T> f(T t) -> f<typename boost::call_traits<T>::type>;
>  
> f(7);                   // Pass by-value
> f(vector {1, 2, 3, 4}); // Passed by const &
> ```

Another drawback of overloading with `requires` is that it can interfere with user-defined overloads, resulting in ambiguity. For example, a Cpp1 `void foo(std::integral auto);`.
